/* **************************************************************************
 *                                                            *
 * **************************************************************************
 * This code contains copyright information which is the proprietary property
 * of   Application Solutions. No part of this code may be reproduced,
 * stored or transmitted in any form without the prior written permission of
 *   Application Solutions.
 *
 * Copyright   Application Solutions 2008
 * All rights reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.08.11 at 05:07:13 PM BST
//
package abc.xyz.pts.bcs.common.dto;

import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for PR_ADD_GENERATED_REPORT complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="PR_ADD_GENERATED_REPORT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="USERNAME" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="REPORT_NAME" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="REPORT_FORMAT" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="REPORT_PARAMETERS" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="STATUS" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="GENERATED_REPORT_ID" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="CREATED_DATETIME" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PR_ADD_GENERATED_REPORT", namespace = "PR_ADD_GENERATED_REPORT")
public class PrAddGeneratedReport {

    @XmlAttribute(name = "USERNAME")
    private String username;
    @XmlAttribute(name = "REPORT_NAME")
    private String reportName;
    @XmlAttribute(name = "REPORT_FORMAT")
    private String reportFormat;
    @XmlAttribute(name = "REPORT_PARAMETERS")
    private String reportParameters;
    @XmlAttribute(name = "STATUS")
    private String status;
    @XmlAttribute(name = "GENERATED_REPORT_ID")
    private Long generatedReportId;
    @XmlAttribute(name = "CREATED_DATETIME")
    private Date createdDatetime;

    /**
     * Gets the value of the username property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setUsername(final String value) {
        this.username = value;
    }

    /**
     * Gets the value of the reportName property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getReportName() {
        return reportName;
    }

    /**
     * Sets the value of the reportName property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setReportName(final String value) {
        this.reportName = value;
    }

    /**
     * Gets the value of the reportFormat property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getReportFormat() {
        return reportFormat;
    }

    /**
     * Sets the value of the reportFormat property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setReportFormat(final String value) {
        this.reportFormat = value;
    }

    /**
     * Gets the value of the reportParameters property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getReportParameters() {
        return reportParameters;
    }

    /**
     * Sets the value of the reportParameters property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setReportParameters(final String value) {
        this.reportParameters = value;
    }

    /**
     * Gets the value of the status property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setStatus(final String value) {
        this.status = value;
    }

    /**
     * Gets the value of the generatedReportId property.
     *
     * @return possible object is {@link Long }
     *
     */
    public Long getGeneratedReportId() {
        return generatedReportId;
    }

    /**
     * Sets the value of the generatedReportId property.
     *
     * @param value
     *            allowed object is {@link Long }
     *
     */
    public void setGeneratedReportId(final Long value) {
        this.generatedReportId = value;
    }

    public Date getCreatedDatetime() {
        return createdDatetime;
    }

    public void setCreatedDatetime(final Date createdDatetime) {
        this.createdDatetime = createdDatetime;
    }

}
