/* **************************************************************************
 *                                                            *
 * **************************************************************************
 * This code contains copyright information which is the proprietary property
 * of   Application Solutions. No part of this code may be reproduced,
 * stored or transmitted in any form without the prior written permission of
 *   Application Solutions.
 *
 * Copyright   Application Solutions 2008
 * All rights reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.08.11 at 05:07:13 PM BST
//

package abc.xyz.pts.bcs.common.dto;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for PR_GET_REPORT complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="PR_GET_REPORT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="P_GENERATED_REPORT_RC" type="{GENERATED_REPORT_RC_REC}GENERATED_REPORT_RC_REC" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="USERNAME" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="NUM_RECORDS" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="QUERY_COUNT" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PR_GET_REPORT", namespace = "PR_GET_REPORT", propOrder = { "pGeneratedReportRc" })
public class PrGetReport {

    @XmlElement(name = "P_GENERATED_REPORT_RC", required = true)
    protected List<GeneratedReportRcRec> pGeneratedReportRc;
    @XmlAttribute(name = "USERNAME")
    protected String username;
    @XmlAttribute(name = "NUM_RECORDS")
    protected Long numRecords;
    @XmlAttribute(name = "QUERY_COUNT")
    protected Long queryCount;

    /**
     * Gets the value of the pGeneratedReportRc property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
     * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the pGeneratedReportRc property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getPGeneratedReportRc().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link GeneratedReportRcRec }
     *
     *
     */
    public List<GeneratedReportRcRec> getPGeneratedReportRc() {
        if (pGeneratedReportRc == null) {
            pGeneratedReportRc = new ArrayList<GeneratedReportRcRec>();
        }
        return this.pGeneratedReportRc;
    }

    /**
     * Gets the value of the username property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setUsername(final String value) {
        this.username = value;
    }

    /**
     * Gets the value of the numRecords property.
     *
     * @return possible object is {@link Long }
     *
     */
    public Long getNumRecords() {
        return numRecords;
    }

    /**
     * Sets the value of the numRecords property.
     *
     * @param value
     *            allowed object is {@link Long }
     *
     */
    public void setNumRecords(final Long value) {
        this.numRecords = value;
    }

    /**
     * Gets the value of the queryCount property.
     *
     * @return possible object is {@link Long }
     *
     */
    public Long getQueryCount() {
        return queryCount;
    }

    /**
     * Sets the value of the queryCount property.
     *
     * @param value
     *            allowed object is {@link Long }
     *
     */
    public void setQueryCount(final Long value) {
        this.queryCount = value;
    }
}
