/* **************************************************************************
 *                                                            *
 * **************************************************************************
 * This code contains copyright information which is the proprietary property
 * of   Application Solutions. No part of this code may be reproduced,
 * stored or transmitted in any form without the prior written permission of
 *   Application Solutions.
 *
 * Copyright   Application Solutions 2008
 * All rights reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.08.11 at 05:07:13 PM BST
//

package abc.xyz.pts.bcs.common.dto;

import java.util.Calendar;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import org.w3._2001.xmlschema.Adapter1;

/**
 * <p>
 * Java class for PR_GET_REPORT_IMAGE complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="PR_GET_REPORT_IMAGE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="GENERATED_REPORT_ID" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="REPORT_IMAGE" type="{http://www.w3.org/2001/XMLSchema}hexBinary" />
 *       &lt;attribute name="REPORT_FORMAT" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="REPORT_NAME" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="REPORT_PARAMETERS" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="REPORT_STATUS" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CREATED_DATETIME" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PR_GET_REPORT_IMAGE", namespace = "PR_GET_REPORT_IMAGE")
public class PrGetReportImage {

    @XmlAttribute(name = "GENERATED_REPORT_ID")
    private Long generatedReportId;
    @XmlAttribute(name = "REPORT_IMAGE")
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    @XmlSchemaType(name = "hexBinary")
    private byte[] reportImage;
    @XmlAttribute(name = "REPORT_FORMAT")
    private String reportFormat;
    @XmlAttribute(name = "REPORT_NAME")
    private String reportName;
    @XmlAttribute(name = "REPORT_PARAMETERS")
    private String reportParameters;
    @XmlAttribute(name = "REPORT_STATUS")
    private String reportStatus;
    @XmlAttribute(name = "CREATED_DATETIME")
    @XmlJavaTypeAdapter(Adapter1.class)
    @XmlSchemaType(name = "dateTime")
    private Calendar createdDatetime;

    /**
     * Gets the value of the generatedReportId property.
     *
     * @return possible object is {@link Long }
     *
     */
    public Long getGeneratedReportId() {
        return generatedReportId;
    }

    /**
     * Sets the value of the generatedReportId property.
     *
     * @param value
     *            allowed object is {@link Long }
     *
     */
    public void setGeneratedReportId(final Long value) {
        this.generatedReportId = value;
    }

    /**
     * Gets the value of the reportImage property.
     *
     * @return possible object is {@link String }
     *
     */
    public byte[] getReportImage() {
        return reportImage;
    }

    /**
     * Sets the value of the reportImage property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setReportImage(final byte[] value) {
        this.reportImage = (byte[])value.clone();
    }

    public String getReportFormat() {
        return reportFormat;
    }

    public void setReportFormat(final String reportFormat) {
        this.reportFormat = reportFormat;
    }

    /**
     * Gets the value of the reportName property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getReportName() {
        return reportName;
    }

    /**
     * Sets the value of the reportName property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setReportName(final String value) {
        this.reportName = value;
    }

    /**
     * Gets the value of the reportParameters property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getReportParameters() {
        return reportParameters;
    }

    /**
     * Sets the value of the reportParameters property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setReportParameters(final String value) {
        this.reportParameters = value;
    }

    /**
     * Gets the value of the reportStatus property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getReportStatus() {
        return reportStatus;
    }

    /**
     * Sets the value of the reportStatus property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setReportStatus(final String value) {
        this.reportStatus = value;
    }

    /**
     * Gets the value of the createdDatetime property.
     *
     * @return possible object is {@link String }
     *
     */
    public Calendar getCreatedDatetime() {
        return createdDatetime;
    }

    /**
     * Sets the value of the createdDatetime property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setCreatedDatetime(final Calendar value) {
        this.createdDatetime = value;
    }
}
