/* **************************************************************************
 *                                                            *
 * **************************************************************************
 * This code contains copyright information which is the proprietary property
 * of   Application Solutions. No part of this code may be reproduced,
 * stored or transmitted in any form without the prior written permission of
 *   Application Solutions.
 *
 * Copyright   Application Solutions 2008
 * All rights reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.08.11 at 05:07:13 PM BST
//

package abc.xyz.pts.bcs.common.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for PR_UPDATE_GENERATED_REPORT complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="PR_UPDATE_GENERATED_REPORT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="GENERATED_REPORT_ID" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="STATUS" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="REPORT_FORMAT" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="REPORT_IMAGE" type="{http://www.w3.org/2001/XMLSchema}hexBinary" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PR_UPDATE_GENERATED_REPORT", namespace = "PR_UPDATE_GENERATED_REPORT")
public class PrUpdateGeneratedReport {

    @XmlAttribute(name = "GENERATED_REPORT_ID")
    private Long generatedReportId;
    @XmlAttribute(name = "STATUS")
    private String status;
    @XmlAttribute(name = "REPORT_FORMAT")
    private String reportFormat;
    @XmlAttribute(name = "REPORT_IMAGE")
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    @XmlSchemaType(name = "hexBinary")
    private byte[] reportImage;

    /**
     * Gets the value of the generatedReportId property.
     *
     * @return possible object is {@link Long }
     *
     */
    public Long getGeneratedReportId() {
        return generatedReportId;
    }

    /**
     * Sets the value of the generatedReportId property.
     *
     * @param value
     *            allowed object is {@link Long }
     *
     */
    public void setGeneratedReportId(final Long value) {
        this.generatedReportId = value;
    }

    /**
     * Gets the value of the status property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setStatus(final String value) {
        this.status = value;
    }

    /**
     * Gets the value of the reportImage property.
     *
     * @return possible object is {@link String }
     *
     */
    public byte[] getReportImage() {
        return reportImage;
    }

    /**
     * Sets the value of the reportImage property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setReportImage(final byte[] value) {
        this.reportImage = (byte[])value.clone();
    }

    public String getReportFormat() {
        return reportFormat;
    }

    public void setReportFormat(final String reportFormat) {
        this.reportFormat = reportFormat;
    }
}
