-- verify CM_PAYEVENT table is created or not

SELECT TO_CHAR('CM_PAYEVENT') VERIFY FROM V_TX.CM_PAYEVENT WHERE '1'='0' UNION ALL SELECT 'The script is verified for CM_PAYEVENT' FROM DUAL;

-- verify CM_PAY_EVENT_STAT table is created or not

SELECT TO_CHAR('CM_PAY_EVENT_STAT') VERIFY FROM V_TX.CM_PAY_EVENT_STAT WHERE '1'='0' UNION ALL SELECT 'The script is verified for CM_PAY_EVENT_STAT' FROM DUAL;

-- verify CM_PAY_EVENT_STAT_REASONS table is created or not

SELECT TO_CHAR('CM_PAY_EVENT_STAT_REASONS') VERIFY FROM V_TX.CM_PAY_EVENT_STAT_REASONS WHERE '1'='0' UNION ALL SELECT 'The script is verified for CM_PAY_EVENT_STAT_REASONS' FROM DUAL;

--verify CM_PAYEVENT_CM_PAY_EVENT_STAT table is created or not

SELECT TO_CHAR('CM_PAYEVENT_CM_PAY_EVENT_STAT') VERIFY FROM V_TX.CM_PAYEVENT_CM_PAY_EVENT_STAT WHERE '1'='0' UNION ALL SELECT 'The script is verified for CM_PAYEVENT_CM_PAY_EVENT_STAT' FROM DUAL;