CREATE INDEX INDEX_OM_STAT_REC_ELEMENT   ON OM_STAT_REC_REASONS(ELEMENT);


CREATE INDEX IDX_LI_STAT_REC_ELE  ON OM_LINE_ITEM_OM_STAT_REC(OM_LINE_ITEM_ID,HISTORICSTATUS_ID);


CREATE INDEX IDX_OM_SO_LI ON OM_SALES_ORDER_OM_LINE_ITEM(OM_SALES_ORDER_ID, LINEITEMS_ID);