COMMENT ON TABLE V_tx.cm_billing_information IS 'This table store customer billing information';

COMMENT ON COLUMN V_tx.cm_billing_information.id IS 'Autogenerated unique id';
COMMENT ON COLUMN V_tx.cm_billing_information.address_external_id IS 'Address external id to which this billing information should be billed';
COMMENT ON COLUMN V_tx.cm_billing_information.billing_method IS 'Type of billing like credit card or check';
COMMENT ON COLUMN V_tx.cm_billing_information.billing_unique_id IS 'Client provided unique id which is referenced in lineitem';
COMMENT ON COLUMN V_tx.cm_billing_information.checking_account_number IS 'Checking account number';
COMMENT ON COLUMN V_tx.cm_billing_information.credit_card_number IS 'Credit card number';
COMMENT ON COLUMN V_tx.cm_billing_information.external_id IS 'System generated external id';
COMMENT ON COLUMN V_tx.cm_billing_information.routing_number IS 'Routing number';
COMMENT ON COLUMN V_tx.cm_billing_information.verification_code IS 'Credit card verification number';
COMMENT ON COLUMN V_tx.cm_billing_information.consumer_id IS 'Customer id to whom this information belongs to';
COMMENT ON COLUMN V_tx.cm_billing_information.card_type IS 'Type of credit card like VISA, MASTER CARD etc';
COMMENT ON COLUMN V_tx.cm_billing_information.expiration_date IS 'Date credit card expires';
COMMENT ON COLUMN V_tx.cm_billing_information.card_holder_name IS 'Card holder name';
COMMENT ON COLUMN V_tx.cm_billing_information.status IS 'Current Status of the Billing Information';

