COMMENT ON TABLE V_tx.om_rules IS 'Rules Information';

COMMENT ON COLUMN V_tx.om_rules.id IS 'Primary key, autogenerated id';
COMMENT ON COLUMN V_tx.om_rules.effective_from_on IS 'Date from which this rule will be active';
COMMENT ON COLUMN V_tx.om_rules.effective_to_on IS 'Date until which this rule should be active';
COMMENT ON COLUMN V_tx.om_rules.description IS 'Description of the rule';
COMMENT ON COLUMN V_tx.om_rules.is_enabled IS 'Is rule enabled or not';
COMMENT ON COLUMN V_tx.om_rules.name IS 'Name of the rule';
COMMENT ON COLUMN V_tx.om_rules.rule_file_name IS 'File name of the rule';