COMMENT ON TABLE V_tx.om_sales_order_context IS 'Information of Sales order context';

COMMENT ON COLUMN V_tx.om_sales_order_context.id IS 'Primary key, autogenerated id';
COMMENT ON COLUMN V_tx.om_sales_order_context.name IS 'Name of the context';
COMMENT ON COLUMN V_tx.om_sales_order_context.order_source IS 'order source';
COMMENT ON COLUMN V_tx.om_sales_order_context.sales_order_id IS 'Order Id';
COMMENT ON COLUMN V_tx.om_sales_order_context.value IS 'Value of the context';
COMMENT ON COLUMN V_tx.om_sales_order_context.entity_name IS 'Entity name of the context';