 
ALTER TABLE  CM_ACCOUNT DROP CONSTRAINT FK_CM_ACCT_CONSUMER;
DROP SEQUENCE  CM_ACCOUNT_SEQ;
DROP   INDEX  IDX_CM_ACCT_CUST;
DROP   INDEX  IDX_CM_ACCT_CUST_EXTID;
DROP TABLE  CM_ACCOUNT ;
 



CREATE SEQUENCE  CM_ACCOUNT_SEQ
    INCREMENT BY 1
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    CACHE 20
    NOORDER;


CREATE TABLE  CM_ACCOUNT ( 
     ID            	bitint NOT NULL,
    ACCT_STATUS   	VARCHAR2(255) NULL,
    ACCT_TYPE     	VARCHAR2(255) NULL,
    ADDR_REF      	VARCHAR2(255) NULL,
    BILL_ACCT_NUM 	VARCHAR2(255) NULL,
    CONSENT_TO_CC 	VARCHAR2(255) NULL,
    CONSUMER_REF  	VARCHAR2(255) NULL,
    CREDIT_ALERT  	VARCHAR2(255) NULL,
    CREDIT_CHECK  	VARCHAR2(255) NULL,
    EXTERNAL_ID   	NUMBER(19,0)  NOT NULL,
    PIN           	VARCHAR2(255) NULL,
    PREV_ADDR_IND 	VARCHAR2(255) NULL,
    PROVIDER_TYPE 	VARCHAR2(255) NULL,
    SEC_ANS       	VARCHAR2(255) NULL,
    SEC_CREDITCARD	VARCHAR2(255) NULL,
    SEC_QUESTION  	VARCHAR2(255) NULL,
    PARTIAL_SSN   	VARCHAR2(255) NULL,
    SUPP_INDICATOR	VARCHAR2(255) NULL,
    CONSUMER_ID   	bigint NOT NULL,
    PRIMARY KEY(ID)
);
 


ALTER TABLE  CM_ACCOUNT
    ADD ( CONSTRAINT FK_CM_ACCT_CONSUMER
	FOREIGN KEY(CONSUMER_ID)
	REFERENCES V_TX.CM_CONSUMER(CONSUMER_ID)
	ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE )
;
 
CREATE   INDEX  IDX_CM_ACCT_CUST ON  CM_ACCOUNT(CONSUMER_ID);
CREATE   INDEX  IDX_CM_ACCT_CUST_EXTID ON  CM_ACCOUNT(CONSUMER_REF);

 