COMMENT ON TABLE V_tx.cm_consumer IS 'This table store customer information';

COMMENT ON COLUMN V_tx.cm_consumer.consumer_id IS 'Autogenerated Customer ID number';
COMMENT ON COLUMN V_tx.cm_consumer.firstname IS 'Customer First Name';
COMMENT ON COLUMN V_tx.cm_consumer.lastname IS 'Customer Last Name';
COMMENT ON COLUMN V_tx.cm_consumer.gender IS 'Customer Gender';
COMMENT ON COLUMN V_tx.cm_consumer.middlename IS 'Customer Middle Name';
COMMENT ON COLUMN V_tx.cm_consumer.namesuffix IS 'Customer Name suffix';
COMMENT ON COLUMN V_tx.cm_consumer.title IS 'Customer Title';
COMMENT ON COLUMN V_tx.cm_consumer.AL_cust_num IS 'System generated AL customer no.';
COMMENT ON COLUMN V_tx.cm_consumer.bill_delivery_pref IS 'Customers billing delivery preference. Possible value Paper or Electronic';
COMMENT ON COLUMN V_tx.cm_consumer.dob IS 'Customer Date of Birth';
COMMENT ON COLUMN V_tx.cm_consumer.driver_license_no IS 'Customer Driver license no.';
COMMENT ON COLUMN V_tx.cm_consumer.employer_bus_name IS 'Customers Employer business name';
COMMENT ON COLUMN V_tx.cm_consumer.employer_phone_num IS 'Customers Employer phone number';
COMMENT ON COLUMN V_tx.cm_consumer.external_id IS 'Customers External ID generated by system for refence inside OME';
COMMENT ON COLUMN V_tx.cm_consumer.landlord_name IS 'Customers Landlord Name';
COMMENT ON COLUMN V_tx.cm_consumer.landlord_phone_no IS 'Customer Landlord phone number';
COMMENT ON COLUMN V_tx.cm_consumer.lic_expiration_date IS 'Customers driver license expiration date';
COMMENT ON COLUMN V_tx.cm_consumer.lic_state IS 'Customers Driver ID state';
COMMENT ON COLUMN V_tx.cm_consumer.occupation IS 'Customers Occupation';
COMMENT ON COLUMN V_tx.cm_consumer.other_income IS 'Customers other source of income';
COMMENT ON COLUMN V_tx.cm_consumer.pin IS 'Customers security question pin number';
COMMENT ON COLUMN V_tx.cm_consumer.region IS 'Customers region';
COMMENT ON COLUMN V_tx.cm_consumer.security_answer IS 'Customers Security Answer';
COMMENT ON COLUMN V_tx.cm_consumer.security_question IS 'Customers security question';
COMMENT ON COLUMN V_tx.cm_consumer.ssn IS 'Customers social security number';
COMMENT ON COLUMN V_tx.cm_consumer.consumer_status IS 'Customers Status';
COMMENT ON COLUMN V_tx.cm_consumer.cellphone_id IS 'Customers Cellphone Id. Referencing id of cm_contact_channel row';
COMMENT ON COLUMN V_tx.cm_consumer.homeemail_id IS 'Customers Home EMail Id. Referencing id of cm_contact_channel row';
COMMENT ON COLUMN V_tx.cm_consumer.homephone_id IS 'Customers Home phone number Id. Referencing id of cm_contact_channel row';
COMMENT ON COLUMN V_tx.cm_consumer.workemail_id IS 'Customers Work email Id. Referencing id of cm_contact_channel row';
COMMENT ON COLUMN V_tx.cm_consumer.workphone_id IS 'Customers work phone Id. Referencing id of cm_contact_channel row';
COMMENT ON COLUMN V_tx.cm_consumer.agent_id IS 'Agent, who has created customer profile';
COMMENT ON COLUMN V_tx.cm_consumer.primary_language IS 'Customers primary language';
COMMENT ON COLUMN V_tx.cm_consumer.directmailoptin IS 'Is customer opted for Direct mail';
COMMENT ON COLUMN V_tx.cm_consumer.email_prod_update_optin IS 'Is Customer opted for product updates email.';
COMMENT ON COLUMN V_tx.cm_consumer.is_employed IS 'Is Customer employed or not.';
COMMENT ON COLUMN V_tx.cm_consumer.marketing_opt_in IS 'Is customer opted for marketing information';
COMMENT ON COLUMN V_tx.cm_consumer.non_buyer_opt_in IS 'Is customer opted for Non-Buyer option';
COMMENT ON COLUMN V_tx.cm_consumer.phone_contact_optin IS 'Is customer opted to be contacted over phone.';
COMMENT ON COLUMN V_tx.cm_consumer.is_retired IS 'Is Customer retired.';
COMMENT ON COLUMN V_tx.cm_consumer.is_student IS 'Is Customer a student';
COMMENT ON COLUMN V_tx.cm_consumer.emailoptin IS 'Is customer opted for Email';

COMMENT ON COLUMN V_tx.cm_consumer.referrer_id IS 'Utility partner who transferred customer to AL';

COMMENT ON COLUMN V_tx.cm_consumer.partner_acct_id IS 'Customer account id in partner system';
COMMENT ON COLUMN V_tx.cm_consumer.best_time_to_call1 IS 'First Best time to call customer with date and time';
COMMENT ON COLUMN V_tx.cm_consumer.best_time_to_call2 IS 'Second Best time to call customer with date and time';

COMMENT ON COLUMN V_tx.cm_consumer.best_time_to_call_phn IS 'Best contact number';
COMMENT ON COLUMN V_tx.cm_consumer.best_email_contact IS 'Best email contact';
COMMENT ON COLUMN V_tx.cm_consumer.current_employed_year IS 'Current employed year';
COMMENT ON COLUMN V_tx.cm_consumer.current_employed_month IS 'Current employed month';

COMMENT ON COLUMN V_tx.cm_consumer.dt_agent_id IS 'Utility partner agent id who transferred the customer to AL';
COMMENT ON COLUMN V_tx.cm_consumer.dt_created IS 'Date when customer was transferred, if client will not provide this date then sytem date time will be stored';

COMMENT ON COLUMN V_tx.cm_consumer.home_phone_value IS 'Customer home phone number';
COMMENT ON COLUMN V_tx.cm_consumer.cell_phone_value IS 'Customer cell phone number';
COMMENT ON COLUMN V_tx.cm_consumer.work_phone_value IS 'Customer work phone number';
COMMENT ON COLUMN V_tx.cm_consumer.home_email_value IS 'Customer home email address';
COMMENT ON COLUMN V_tx.cm_consumer.work_email_value IS 'Customer work email address';
COMMENT ON COLUMN V_tx.cm_consumer.customer_type IS 'Customer type';
COMMENT ON COLUMN V_tx.cm_consumer.best_phone_contact IS 'Customer best contact number'; 
COMMENT ON COLUMN V_tx.cm_consumer.partner_name IS 'Customer partner name';  
COMMENT ON COLUMN V_tx.cm_consumer.partner_ssn IS 'Customer partner ssn';  
COMMENT ON COLUMN V_tx.cm_consumer.second_phone IS 'Customer second phone number';   
COMMENT ON COLUMN V_tx.cm_consumer.ssn_last_four IS 'Customer last 4 ssn';
   
COMMENT ON COLUMN V_tx.cm_consumer.BIRTH_INFO IS 'birth information for consumer.  encrypted.';
 
   




