ALTER TABLE V_tx.om_line_item ADD COLUMN is_new integer default 0;
ALTER TABLE V_tx.OM_LINE_ITEM ADD COLUMN DISCONNECT_ON TIMESTAMP NULL ;
ALTER TABLE V_tx.OM_LINE_ITEM ADD COLUMN ORDERED_ON TIMESTAMP NULL ;