CREATE TABLE V_TX.OM_RTIM_ORDER_MAPPING
(
  ID NUMERIC(19, 0) NOT NULL
, V_ORDER_NO character varying(20)
, ORDER_EXT_ID NUMERIC(19, 0)
, LI_EXT_ID NUMERIC(19, 0)
, PROVIDER_EXT_ID character varying(20)
, DT_CREATED TIMESTAMP
, CONTEXT character varying(20)
, DESCRIPTION character varying(1500)
);

ALTER TABLE V_TX.OM_RTIM_ORDER_MAPPING ADD CONSTRAINT pk_om_rtim_order_mapping PRIMARY KEY(id);

ALTER TABLE V_TX.OM_RTIM_ORDER_MAPPING ADD CONSTRAINT unq_om_rtim_order_mapping UNIQUE(V_ORDER_NO,ORDER_EXT_ID,LI_EXT_ID);

CREATE SEQUENCE V_TX.OM_RTIM_ORDER_MAPPING_SEQ INCREMENT BY 1 START WITH 1 CACHE 20;


