ALTER TABLE UAM_RESOURCE DROP COLUMN    RESOURCE_NAME;
ALTER TABLE UAM_RESOURCE DROP COLUMN    RESOURCE_DESC;

ALTER TABLE UAM_RESOURCE ADD COLUMN    RESOURCE_NAME character varying(120);
ALTER TABLE UAM_RESOURCE ADD COLUMN    RESOURCE_DESC character varying(120);