ALTER TABLE V_TX.OM_LINE_ITEM ADD COLUMN    PARTNER_EXT_ID character varying(60);
  
ALTER TABLE UAM_RESOURCE DROP COLUMN    DESIRED_START_REQ;
ALTER TABLE UAM_RESOURCE ADD COLUMN    DESIRED_START_REQ text;