COMMENT ON TABLE V_tx.om_sel_dialogue IS 'Dialogue Information';

COMMENT ON COLUMN V_tx.om_sel_dialogue.id IS 'Primary Key, autogenerated id';
COMMENT ON COLUMN V_tx.om_sel_dialogue.external_id IS 'Dialogue Id';
COMMENT ON COLUMN V_tx.om_sel_dialogue.dialogue_value IS 'Value of the dialogue';
COMMENT ON COLUMN V_tx.om_sel_dialogue.is_selected IS 'Is dialogue selected or not';
COMMENT ON COLUMN V_tx.om_sel_dialogue.dialogue_value_type IS 'Datatype of Dialogue value';
COMMENT ON COLUMN V_tx.om_sel_dialogue.dialogue_date IS 'Date of the Dialogue';