SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='CM_CONSUMER' AND COLUMN_NAME ='SSN_LAST_FOUR';
SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='CM_BILLING_INFORMATION' AND COLUMN_NAME ='EXPIRE_MONTH' AND DATA_LENGTH=1000;
SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='CM_BILLING_INFORMATION' AND COLUMN_NAME ='EXPIRE_YEAR' AND DATA_LENGTH=1000;

SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='CM_BILLING_INFORMATION' AND COLUMN_NAME ='CREDIT_CARD_NUMBER' AND DATA_LENGTH=1000;
SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='CM_BILLING_INFORMATION' AND COLUMN_NAME ='CARD_HOLDER_NAME' AND DATA_LENGTH=1000;


SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='CM_CONSUMER' AND COLUMN_NAME ='REFERRER_GENERAL_NAME';

