-- verify create table

SELECT TO_CHAR('OM_JOB') VERIFY FROM V_TX.OM_JOB WHERE '1'='0' UNION ALL SELECT 'The script is verified for OM_JOB' FROM DUAL;

-- verify primary key

SELECT '1' AS Expected, COUNT(*) AS Actual FROM DUAL WHERE (SELECT CONSTRAINT_NAME FROM ALL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'PK_OM_JOB') IN ('PK_OM_JOB');

-- verify sequence

SELECT '1' AS Expected, COUNT(*) AS Actual FROM DUAL WHERE (SELECT SEQUENCE_NAME FROM ALL_SEQUENCES WHERE SEQUENCE_NAME ='OM_JOB_SEQ') IN ('OM_JOB_SEQ');

--verify index

SELECT '1' AS Expected, COUNT(*) AS Actual FROM DUAL WHERE (SELECT INDEX_NAME FROM ALL_INDEXES WHERE INDEX_NAME ='IDX_OM_STAT_REC_ELEMENT') IN ('IDX_OM_STAT_REC_ELEMENT');
SELECT '1' AS Expected, COUNT(*) AS Actual FROM DUAL WHERE (SELECT INDEX_NAME FROM ALL_INDEXES WHERE INDEX_NAME ='IDX_LI_STAT_REC_ELE') IN ('IDX_LI_STAT_REC_ELE');
SELECT '1' AS Expected, COUNT(*) AS Actual FROM DUAL WHERE (SELECT INDEX_NAME FROM ALL_INDEXES WHERE INDEX_NAME ='IDX_OM_SO_LI') IN ('IDX_OM_SO_LI');

-- verify col added in om_lineitem

SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_LINE_ITEM' AND COLUMN_NAME ='NEW_PHONE';

-- verify create table

SELECT TO_CHAR('OM_LI_ATTRIBUTE') VERIFY FROM V_TX.OM_LI_ATTRIBUTE WHERE '1'='0' UNION ALL SELECT 'The script is verified for OM_LI_ATTRIBUTE' FROM DUAL;

-- verify primary key

SELECT '1' AS Expected, COUNT(*) AS Actual FROM DUAL WHERE (SELECT CONSTRAINT_NAME FROM ALL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'PK_OM_LINE_ITEM_ATTRIBUTE') IN ('PK_OM_LINE_ITEM_ATTRIBUTE');

-- verify sequence

SELECT '1' AS Expected, COUNT(*) AS Actual FROM DUAL WHERE (SELECT SEQUENCE_NAME FROM ALL_SEQUENCES WHERE SEQUENCE_NAME ='OM_LINE_ITEM_ATTRIBUTE_SEQ') IN ('OM_LINE_ITEM_ATTRIBUTE_SEQ');

-- verify create table

SELECT TO_CHAR('OM_LINE_ITEM_OM_LI_ATTRIBUTE') VERIFY FROM V_TX.OM_LINE_ITEM_OM_LI_ATTRIBUTE WHERE '1'='0' UNION ALL SELECT 'The script is verified for OM_LINE_ITEM_OM_LI_ATTRIBUTE' FROM DUAL;

-- verify foreign key

SELECT '1' AS Expected, COUNT(*) AS Actual FROM DUAL WHERE (SELECT CONSTRAINT_NAME FROM ALL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_OM_LINE_ITEM_OM_LI_ATTRIB') IN ('FK_OM_LINE_ITEM_OM_LI_ATTRIB');

-- verify col added in om_lineitem

SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_SALES_ORDER_CONTEXT' AND COLUMN_NAME ='ENTITY_NAME';

-- verify create table

SELECT TO_CHAR('OM_SYSTEM_REASON') VERIFY FROM V_TX.OM_SYSTEM_REASON WHERE '1'='0' UNION ALL SELECT 'The script is verified for OM_SYSTEM_REASON' FROM DUAL;

