SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_SEL_FEATURE' AND COLUMN_NAME ='IS_ACTIVE';

SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_SEL_FEATURE' AND COLUMN_NAME ='FEATURE_DATE';

SELECT '1' AS Expected, COUNT(*) AS Actual FROM DUAL WHERE (SELECT INDEX_NAME FROM ALL_INDEXES WHERE INDEX_NAME ='IDX_SF_ACTIVEFLAG') in ('IDX_SF_ACTIVEFLAG');