-- INCREASING THE COL SIZE TO FIT ENCRYPTED STRING

ALTER TABLE V_TX.CM_CONSUMER ALTER COLUMN BIRTH_INFO TYPE character varying(5000);
ALTER TABLE V_TX.CM_CONSUMER ALTER COLUMN DRIVER_LICENSE_NO TYPE character varying(5000);
ALTER TABLE V_TX.CM_CONSUMER ALTER COLUMN SSN TYPE character varying(5000);
ALTER TABLE V_TX.CM_CONSUMER ALTER COLUMN PIN TYPE character varying(5000);
ALTER TABLE V_TX.CM_CONSUMER ALTER COLUMN SECURITY_ANSWER TYPE character varying(5000);
ALTER TABLE V_TX.CM_CONSUMER ALTER COLUMN PARTNER_SSN TYPE character varying(5000);

ALTER TABLE V_TX.CM_BILLING_INFORMATION ALTER COLUMN EXPIRE_MONTH TYPE character varying(5000);
ALTER TABLE V_TX.CM_BILLING_INFORMATION ALTER COLUMN EXPIRE_YEAR TYPE character varying(5000);
ALTER TABLE V_TX.CM_BILLING_INFORMATION ALTER COLUMN CREDIT_CARD_NUMBER  TYPE character varying(5000);
ALTER TABLE V_TX.CM_BILLING_INFORMATION ALTER COLUMN CARD_HOLDER_NAME  TYPE character varying(5000);
ALTER TABLE V_TX.CM_BILLING_INFORMATION ALTER COLUMN CHECKING_ACCOUNT_NUMBER TYPE character varying(5000);
ALTER TABLE V_TX.CM_BILLING_INFORMATION ALTER COLUMN ROUTING_NUMBER TYPE character varying(5000);


ALTER TABLE V_TX.OM_JOB ALTER COLUMN STATUS_QUEUED TYPE character varying(50);

