-- setting Direct Star as non-realtime provider
UPDATE V_LOGICAL_1.BUSINESSPARTY SET REALTIME_PROVIDER=1 WHERE EXTERNALID='2314635';

-- setting ADT Security as non-realtime provider
UPDATE V_LOGICAL_1.BUSINESSPARTY SET REALTIME_PROVIDER=1 WHERE EXTERNALID='4142189';

-- setting Living Social as non-realtime provider
UPDATE V_LOGICAL_1.BUSINESSPARTY SET REALTIME_PROVIDER=1 WHERE EXTERNALID='21770432';

-- setting Dominion Prod and Services as non-realtime provider
UPDATE V_LOGICAL_1.BUSINESSPARTY SET REALTIME_PROVIDER=1 WHERE EXTERNALID='10513134';

-- setting Home Depot as non-realtime provider
UPDATE V_LOGICAL_1.BUSINESSPARTY SET REALTIME_PROVIDER=1 WHERE EXTERNALID='18486164';