-- verify create table

SELECT TO_CHAR('OM_RTIM_ORDER_MAPPING') VERIFY FROM V_TX.OM_RTIM_ORDER_MAPPING WHERE '1'='0' UNION ALL SELECT 'The script is verified for OM_RTIM_ORDER_MAPPING' FROM DUAL;

-- verify sequence

SELECT '1' AS Expected, COUNT(*) AS Actual FROM DUAL WHERE (SELECT SEQUENCE_NAME FROM ALL_SEQUENCES WHERE SEQUENCE_NAME ='OM_RTIM_ORDER_MAPPING_SEQ') IN ('OM_RTIM_ORDER_MAPPING_SEQ');