SELECT '1' AS Expected, COUNT(*) AS Actual FROM DUAL WHERE (SELECT INDEX_NAME FROM ALL_INDEXES WHERE INDEX_NAME ='OM_BRDCST_DWME_STAT_IDX01') in ('OM_BRDCST_DWME_STAT_IDX01');

SELECT '1' AS Expected, COUNT(*) AS Actual FROM DUAL WHERE (SELECT INDEX_NAME FROM ALL_INDEXES WHERE INDEX_NAME ='OM_BRDCST_CCP_STAT_IDX01') in ('OM_BRDCST_CCP_STAT_IDX01');

SELECT '1' AS Expected, COUNT(*) AS Actual FROM DUAL WHERE (SELECT INDEX_NAME FROM ALL_INDEXES WHERE INDEX_NAME ='OM_BRDCST_DM_STAT_IDX01') in ('OM_BRDCST_DM_STAT_IDX01');