ALTER TABLE OM_LINE_ITEM  DROP NON_RECUR_PRICE_U;
ALTER TABLE OM_LINE_ITEM  DROP RECUR_PRICE_U;
ALTER TABLE OM_LINE_ITEM  DROP INC_PRICE;


ALTER TABLE OM_SALES_ORDER  DROP NON_RECUR_PRICE_U;
ALTER TABLE OM_SALES_ORDER  DROP RECUR_PRICE_U;

