ALTER TABLE CM_CONSUMER DROP COLUMN    BEST_PHONE_CONTACT;
ALTER TABLE CM_CONSUMER DROP COLUMN    PARTNER_NAME;
ALTER TABLE CM_CONSUMER DROP COLUMN    PARTNER_SSN;
ALTER TABLE CM_CONSUMER DROP COLUMN    SECOND_PHONE;