ALTER TABLE V_TX.OM_LINE_ITEM DROP COLUMN    PARTNER_EXT_ID;

ALTER TABLE UAM_RESOURCE DROP COLUMN    DESIRED_START_REQ;
ALTER TABLE UAM_RESOURCE ADD COLUMN    DESIRED_START_REQ character varying(255);