COMMENT ON TABLE V_tx.cm_consumer_interaction IS 'Stores customer interaction information';

COMMENT ON COLUMN V_tx.cm_consumer_interaction.id IS 'Autogenerated unique id';
COMMENT ON COLUMN V_tx.cm_consumer_interaction.agent_ext_id IS 'Agent external id to whom customer interacted';
COMMENT ON COLUMN V_tx.cm_consumer_interaction.consumer_external_id IS 'Customer external id';
COMMENT ON COLUMN V_tx.cm_consumer_interaction.interaction_on IS 'Date when interaction occured';
COMMENT ON COLUMN V_tx.cm_consumer_interaction.notes IS 'Agent supplied notes about interaction';
COMMENT ON COLUMN V_tx.cm_consumer_interaction.order_ext_id IS 'Order external id. Could be null if there is no order for the customer';
COMMENT ON COLUMN V_tx.cm_consumer_interaction.source IS 'Source of the interaction. Like call center or web if customer logged in to AL site';


