package abc.xyz.pts.bcs.common.audit.business;

public enum Event{
    //Do no edit this file. It is generated by the CommonAudit EnumGenerator.
    <!--EVENT_NAMES-->
    
    private final String value;
    
    Event(String value){
            this.value = value;
    }
    
    public String value(){
            return value;
    } 
}