package abc.xyz.pts.bcs.common.audit.business;

public enum Parameter{
    //Do no edit this file. It is generated by the CommonAudit EnumGenerator.
    <!--PARAMETER_NAMES-->
    
    private final String value;
    
    Parameter(String value){
            this.value = value;
    }
    
    public String value(){
            return value;
    } 
}