COMMENT ON TABLE V_tx.cm_contact_channel IS 'This table store customer contact information';

COMMENT ON COLUMN V_tx.cm_contact_channel.id IS 'Autogenerated unique ID number';
COMMENT ON COLUMN V_tx.cm_contact_channel.channeltype IS 'Type of contact channel like phone,email';
COMMENT ON COLUMN V_tx.cm_contact_channel.consumer_external_id IS 'Customer external id';
COMMENT ON COLUMN V_tx.cm_contact_channel.description IS 'Description';
COMMENT ON COLUMN V_tx.cm_contact_channel.preferenceorder IS 'Preference order';
COMMENT ON COLUMN V_tx.cm_contact_channel.value IS 'Actual value of either phone no or email address';
