SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='CM_ACCOUNT' AND COLUMN_NAME ='CONSUMER_ID';

SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_JOB' AND COLUMN_NAME ='LOCKED_AT';
SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_JOB' AND COLUMN_NAME ='EFFECTIVE_FROM_ON';
SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_JOB' AND COLUMN_NAME ='EFFECTIVE_TO_ON';

SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_LINE_ITEM' AND COLUMN_NAME ='DESIRED_START_EE_ON';
SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_LINE_ITEM' AND COLUMN_NAME ='SCHEDULED_START_EE_ON';
SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_LINE_ITEM' AND COLUMN_NAME ='ACTUAL_START_EE_ON';
SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_LINE_ITEM' AND COLUMN_NAME ='DISCONNECT_EE_ON';
SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_LINE_ITEM' AND COLUMN_NAME ='DESIRED_START_REQ';

SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='CM_CONSUMER' AND COLUMN_NAME ='CUSTOMER_TYPE';

SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_JOB' AND COLUMN_NAME ='CUSTOMER_ID';

SELECT '1' AS Expected, COUNT(*) AS Actual FROM DUAL WHERE (SELECT SEQUENCE_NAME FROM ALL_SEQUENCES WHERE SEQUENCE_NAME ='CM_PAYEVENT_SEQ') IN ('CM_PAYEVENT_SEQ');

SELECT '1' AS Expected, COUNT(*) AS Actual FROM DUAL WHERE (SELECT SEQUENCE_NAME FROM ALL_SEQUENCES WHERE SEQUENCE_NAME ='CM_PAY_EVENT_STAT_SEQ') IN ('CM_PAY_EVENT_STAT_SEQ');

SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='CM_PAYEVENT' AND COLUMN_NAME ='CC_DISCLOSURE';