 
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.Marshaller;

//import com.A.xml.v4.AuthenticateUserRequest;
//import com.A.xml.v4.AuthenticateUserRequestType;
//import com.A.xml.v4.Credential;
//import com.A.xml.v4.EnterpriseRequestDocumentType;
//import com.A.xml.v4.UamTransactionTypeType;
//import com.A.xml.v4.WebServiceProxyService;
//import com.A.xml.v4.WebServiceProxyServicePortType;

/**
 * This class was generated by Apache CXF 2.5.2 2012-01-31T09:12:03.290-05:00
 * Generated source version: 2.5.2
 * 
 */
public final class TestUAMClient {

	private static final QName SERVICE_NAME = new QName(
			"http://xml.A.com/v4", "WebServiceProxyService");

	private TestUAMClient() {
	}

	public static void main(String args[]) throws java.lang.Exception {
//		URL wsdlURL = WebServiceProxyService.WSDL_LOCATION;
//		if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
//			File wsdlFile = new File(args[0]);
//			try {
//				if (wsdlFile.exists()) {
//					wsdlURL = wsdlFile.toURI().toURL();
//				} else {
//					wsdlURL = new URL(args[0]);
//				}
//			} catch (MalformedURLException e) {
//				e.printStackTrace();
//			}
//		}
//
//		WebServiceProxyService ss = new WebServiceProxyService(wsdlURL,
//				SERVICE_NAME);
//		WebServiceProxyServicePortType port = ss
//				.getWebServiceProxyServicePort();
//
//		{
//			System.out.println("Invoking manageUser...");
//			EnterpriseRequestDocumentType enterpriseRequestDocument = new EnterpriseRequestDocumentType();
//			UamTransactionTypeType uamTransactionType = new UamTransactionTypeType();
//
//		 
//			 
//			uamTransactionType.setUamTransactionType("authenticateUser");
//			enterpriseRequestDocument.setTransactionType(uamTransactionType);
//			enterpriseRequestDocument.setGUID("1234");
//			
//			 
//			AuthenticateUserRequestType authenticateUserRequest = new AuthenticateUserRequestType();
//			AuthenticateUserRequest aur = new AuthenticateUserRequest();
//		 
//			
//			enterpriseRequestDocument.setRequest(authenticateUserRequest);
//			
//			aur.setSuperVisorUserName("supervisorName");
//			enterpriseRequestDocument.setRequest(authenticateUserRequest);
//			authenticateUserRequest.setAuthenticateUserRequest(aur);
//
//			aur.setUserName("AmetUser");
//			 
//
//			Credential cred = new Credential();
//			cred.setCredentialName("password");
//
//			aur.setCredentials(cred);
//
//			JAXBContext jc = JAXBContext
//					.newInstance(EnterpriseRequestDocumentType.class);
//
//			Marshaller marshaller = jc.createMarshaller();
//			marshaller.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, true);
//			JAXBElement<EnterpriseRequestDocumentType> jaxbElement = new JAXBElement<EnterpriseRequestDocumentType>(
//					new QName("uamEnterpriseRequest"),
//					EnterpriseRequestDocumentType.class, enterpriseRequestDocument);
//			marshaller.marshal(jaxbElement, System.out);
//
//			// com.A.xml.v4.EnterpriseResponseDocumentType
//			// _manageUser__return =(EnterpriseResponseDocumentType)
//			 
//			// System.out.println("manageUser.result=" +
//			// port.manageUser(params));
//
//		}
//
//		System.exit(0);
 	}

}
