SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_SEL_FEATURE' AND COLUMN_NAME='NON_RECUR_PRICE_U' AND DATA_DEFAULT='''USD''::character varying';

SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_SEL_FEATURE' AND COLUMN_NAME='RECUR_PRICE_U' AND DATA_DEFAULT='''USD''::character varying';

SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_SEL_FEATURE' AND COLUMN_NAME='IS_REQUIRED' AND DATA_DEFAULT='true';

--SELECT '1' as EXPECTED, COUNT(*) FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_SEL_FEATURE' AND COLUMN_NAME='ON_DELIVERY_PRICE' AND DATA_TYPE='NUMBER' AND DATA_PRECISION=19 AND DATA_SCALE=3;

SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='CM_ACCOUNT' AND COLUMN_NAME='IS_AUTHORIZED' AND DATA_TYPE='INTEGER';


SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_JOB' AND COLUMN_NAME='REASON' AND DATA_DEFAULT='''';


SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_JOB' AND COLUMN_NAME='REASON' AND DATA_DEFAULT='''''::character varying';


