/* This code contains copyright information which is the proprietary property
 * of   Advanced Travel Solutions. No part of this code may be reproduced,
 * stored or transmitted in any form without the prior written permission of
 *   Advanced Travel Solutions.
 *
 * Copyright   Advanced Travel Solutions 2011
 * Confidential. All rights reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.03.26 at 04:27:53 PM GMT
//

package abc.xyz.pts.bcs.wi.dto;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import org.w3._2001.xmlschema.Adapter1;

/**
 * <p>
 * Java class for PR_LIST_TARGET_ITEM complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="PR_LIST_TARGET_ITEM">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="P_TARGET_ITEM_RC" type="{TARGET_ITEM_RC_REC}TARGET_ITEM_RC_REC" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="FORENAME" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="LAST_NAME" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="DOC_TYPE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="DOC_NUMBER" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="NATIONALITY" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="BIRTH_DATE" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="BIRTH_PLACE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="GENDER" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="VALID_UNTIL_DATE" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="RECOMMENDED_ACTION" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="PROTOCOL_NUMBER" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="NUM_RECORDS" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="QUERY_COUNT" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PR_LIST_TARGET_ITEM", namespace = "PR_LIST_TARGET_ITEM", propOrder = { "targetItemList" })
public class TargetItemList {

    @XmlElement(name = "P_TARGET_ITEM_RC", required = true)
    private List<TargetItem> targetItemList;
    @XmlAttribute(name = "FORENAME")
    private String forename;
    @XmlAttribute(name = "LAST_NAME")
    private String lastName;
    @XmlAttribute(name = "DOC_TYPE")
    private String docType;
    @XmlAttribute(name = "DOC_NUMBER")
    private String docNumber;
    @XmlAttribute(name = "NATIONALITY")
    private String nationality;
    @XmlAttribute(name = "BIRTH_DATE")
    @XmlJavaTypeAdapter(Adapter1.class)
    @XmlSchemaType(name = "dateTime")
    private Calendar birthDate;
    @XmlAttribute(name = "BIRTH_DATE_TO")
    @XmlJavaTypeAdapter(Adapter1.class)
    @XmlSchemaType(name = "dateTime")
    private Calendar birthDateTo;
    @XmlAttribute(name = "BIRTH_PLACE")
    private String birthPlace;
    @XmlAttribute(name = "GENDER")
    private String gender;
    @XmlAttribute(name = "VALID_UNTIL_DATE")
    @XmlJavaTypeAdapter(Adapter1.class)
    @XmlSchemaType(name = "dateTime")
    private Calendar validUntilDate;
    @XmlAttribute(name = "RECOMMENDED_ACTION")
    private String recommendedAction;
    @XmlAttribute(name = "PROTOCOL_NUMBER")
    private String protocolNumber;
    @XmlAttribute(name = "NUM_RECORDS")
    private Long numRecords;
    @XmlAttribute(name = "QUERY_COUNT")
    private Long queryCount;
    @XmlAttribute(name = "ORDER_BY_COL")
    private String orderByCol;
    @XmlAttribute(name = "ASC_DESC")
    private String ascDesc;
    @XmlAttribute(name = "COUNTRY_OF_BIRTH")
    private String countryOfBirth;
    @XmlAttribute(name = "RESC_CODE")   // reason code
    private String rescCode;
    @XmlAttribute(name = "WATCH_LIST_NAME")
    private String watchListName;
    @XmlAttribute(name = "SEVERITY_LEVEL")   // reason code
    private String severityLevel;


    /**
     * Gets the value of the targetItemList property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
     * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the targetItemList property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getPTargetItemRc().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link TargetItemRcRec }
     *
     *
     */
    public List<TargetItem> getTargetItemList() {
        if (targetItemList == null) {
            targetItemList = new ArrayList<TargetItem>();
        }
        return this.targetItemList;
    }

    /**
     * Gets the value of the forename property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getForename() {
        return forename;
    }

    /**
     * Sets the value of the forename property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setForename(final String value) {
        this.forename = value;
    }

    /**
     * Gets the value of the lastName property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setLastName(final String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the docType property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getDocType() {
        return docType;
    }

    /**
     * Sets the value of the docType property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setDocType(final String value) {
        this.docType = value;
    }

    /**
     * Gets the value of the docNumber property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getDocNumber() {
        return docNumber;
    }

    /**
     * Sets the value of the docNumber property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setDocNumber(final String value) {
        this.docNumber = value;
    }

    /**
     * Gets the value of the nationality property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * Sets the value of the nationality property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setNationality(final String value) {
        this.nationality = value;
    }

    /**
     * Gets the value of the birthDate property.
     *
     * @return possible object is {@link String }
     *
     */
    public Calendar getBirthDate() {
        return birthDate;
    }

    /**
     * Sets the value of the birthDate property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setBirthDate(final Calendar value) {
        this.birthDate = value;
    }

    /**
     * Gets the value of the birthPlace property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getBirthPlace() {
        return birthPlace;
    }

    /**
     * Sets the value of the birthPlace property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setBirthPlace(final String value) {
        this.birthPlace = value;
    }

    /**
     * Gets the value of the gender property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setGender(final String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the validUntilDate property.
     *
     * @return possible object is {@link String }
     *
     */
    public Calendar getValidUntilDate() {
        return validUntilDate;
    }

    /**
     * Sets the value of the validUntilDate property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setValidUntilDate(final Calendar value) {
        this.validUntilDate = value;
    }

    /**
     * Gets the value of the recommendedAction property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getRecommendedAction() {
        return recommendedAction;
    }

    /**
     * Sets the value of the recommendedAction property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setRecommendedAction(final String value) {
        this.recommendedAction = value;
    }

    /**
     * Gets the value of the protocolNumber property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getProtocolNumber() {
        return protocolNumber;
    }

    /**
     * Sets the value of the protocolNumber property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setProtocolNumber(final String value) {
        this.protocolNumber = value;
    }

    /**
     * Gets the value of the numRecords property.
     *
     * @return possible object is {@link Long }
     *
     */
    public Long getNumRecords() {
        return numRecords;
    }

    /**
     * Sets the value of the numRecords property.
     *
     * @param value
     *            allowed object is {@link Long }
     *
     */
    public void setNumRecords(final Long value) {
        this.numRecords = value;
    }

    /**
     * Gets the value of the queryCount property.
     *
     * @return possible object is {@link Long }
     *
     */
    public Long getQueryCount() {
        return queryCount;
    }

    /**
     * Sets the value of the queryCount property.
     *
     * @param value
     *            allowed object is {@link Long }
     *
     */
    public void setQueryCount(final Long value) {
        this.queryCount = value;
    }

    /**
     * Gets the value of the orderByCol property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getOrderByCol() {
        return orderByCol;
    }

    /**
     * Sets the value of the orderByCol property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setOrderByCol(final String value) {
        this.orderByCol = value;
    }

    /**
     * Gets the value of the ascDesc property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getAscDesc() {
        return ascDesc;
    }

    /**
     * Sets the value of the ascDesc property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setAscDesc(final String value) {
        this.ascDesc = value;
    }

    public String getCountryOfBirth()
    {
        return countryOfBirth;
    }

    public void setCountryOfBirth(final String countryOfBirth)
    {
        this.countryOfBirth = countryOfBirth;
    }

    public String getRescCode()
    {
        return rescCode;
    }

    public void setRescCode(final String rescCode)
    {
        this.rescCode = rescCode;
    }

    public String getWatchListName()
    {
        return watchListName;
    }

    public void setWatchListName(final String watchListName)
    {
        this.watchListName = watchListName;
    }

    public String getSeverityLevel()
    {
        return severityLevel;
    }

    public void setSeverityLevel(final String severityLevel)
    {
        this.severityLevel = severityLevel;
    }

    public Calendar getBirthDateTo()
    {
        return birthDateTo;
    }

    public void setBirthDateTo(final Calendar birthDateTo)
    {
        this.birthDateTo = birthDateTo;
    }

}