SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='CM_CUSTOMER_INTERACTION' AND COLUMN_NAME ='SERVICE_TYPE';

SELECT '1' AS Expected, COUNT(*) AS Actual FROM DUAL WHERE (SELECT INDEX_NAME FROM ALL_INDEXES WHERE INDEX_NAME ='CM_INTN_ORDID_IDX01') in ('CM_INTN_ORDID_IDX01');

SELECT '1' AS Expected, COUNT(*) AS Actual FROM DUAL WHERE (SELECT INDEX_NAME FROM ALL_INDEXES WHERE INDEX_NAME ='CM_CONS_NAME_IDX01') in ('CM_CONS_NAME_IDX01');

SELECT '1' AS Expected, COUNT(*) AS Actual FROM DUAL WHERE (SELECT INDEX_NAME FROM ALL_INDEXES WHERE INDEX_NAME ='CM_ADDR_ZIP_IDX01') in ('CM_ADDR_ZIP_IDX01');