 SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_SALES_ORDER' AND COLUMN_NAME ='GUID';

 SELECT '1' AS Expected, COUNT(*) AS Actual FROM DUAL WHERE (SELECT INDEX_NAME FROM ALL_INDEXES WHERE INDEX_NAME ='OMSO_GUID_IDX01') in ('OMSO_GUID_IDX01');