SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_LINE_ITEM' AND COLUMN_NAME ='LI_CREATE_DATE' AND DATA_TYPE='TIMESTAMP WITHOUT TIME ZONE';

SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_SEL_DIALOGUE' AND COLUMN_NAME ='DIALOGUE_VALUE' AND DATA_LENGTH=3000;