
SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_CUST_SELECTION' AND COLUMN_NAME ='SELECTION_DISPLAY_ORDER';

SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_CUST_SELECTION' AND COLUMN_NAME ='SELECTION_TYPE';

SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_CUST_SELECTION' AND COLUMN_NAME ='SELECTION_SHORT_DESC';

SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_CUST_SELECTION' AND COLUMN_NAME ='SELECTION_NAME';

SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_CUST_SELECTION' AND COLUMN_NAME ='CHIOCE_DISPLAY_ORDER';

SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_CUST_SELECTION' AND COLUMN_NAME ='CHIOCE_SHORT_DESC';

SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_CUST_SELECTION' AND COLUMN_NAME ='CHIOCE_NAME';

SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_CUST_SELECTION' AND COLUMN_NAME ='BASE_NONRECURRING_PRICE';

SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_CUST_SELECTION' AND COLUMN_NAME ='BASE_RECURRING_PRICE';

SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_CUST_SELECTION' AND COLUMN_NAME ='BASE_NONRECURRING_PRICE_UNITS';

SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_CUST_SELECTION' AND COLUMN_NAME ='BASE_RECURRING_PRICE_UNITS';

SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_CUST_SELECTION' AND COLUMN_NAME ='INCLUDEIN_TOTAL_PRICE';