--verify sys_propeties table exist or not

SELECT TO_CHAR('SYS_PROPERTIES') VERIFY FROM V_TX.SYS_PROPERTIES WHERE '1'='0' UNION ALL SELECT 'The script is verified for SYS_PROPERTIES' FROM DUAL;

-- verify cols added in om_job

SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_JOB' AND COLUMN_NAME ='EXTERNAL_ID';
SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_JOB' AND COLUMN_NAME ='LOCKED_AT';
SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_JOB' AND COLUMN_NAME ='DESC1';
SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_JOB' AND COLUMN_NAME ='DESC2';