SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='CM_CONSUMER' AND COLUMN_NAME ='DT_AGENT_ID';
SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='CM_CONSUMER' AND COLUMN_NAME ='DT_CREATED';

SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='CM_CUSTOMER_INTERACTION' AND COLUMN_NAME ='IS_SYS_CREATED';
SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='CM_CUSTOMER_INTERACTION' AND COLUMN_NAME ='LI_EXT_ID';

SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_LINE_ITEM' AND COLUMN_NAME ='LI_STATE';

-- verify create table

SELECT TO_CHAR('CM_ACCOUNT') VERIFY FROM V_TX.OM_RTIM_ORDER_MAPPING WHERE '1'='0' UNION ALL SELECT 'The script is verified for CM_ACCOUNT' FROM DUAL;

-- verify sequence

SELECT '1' AS Expected, COUNT(*) AS Actual FROM DUAL WHERE (SELECT SEQUENCE_NAME FROM ALL_SEQUENCES WHERE SEQUENCE_NAME ='CM_ACCOUNT_SEQ') IN ('CM_ACCOUNT_SEQ');