SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_LINE_ITEM' AND COLUMN_NAME ='NON_RECUR_PRICE_U';
SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_LINE_ITEM' AND COLUMN_NAME ='RECUR_PRICE_U';
SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_LINE_ITEM' AND COLUMN_NAME ='INC_PRICE';

SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_SALES_ORDER' AND COLUMN_NAME ='NON_RECUR_PRICE_U';
SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_SALES_ORDER' AND COLUMN_NAME ='RECUR_PRICE_U';

 