SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='CM_CONSUMER' AND COLUMN_NAME ='BEST_PHONE_CONTACT';

SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='CM_CONSUMER' AND COLUMN_NAME ='PARTNER_NAME';
SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='CM_CONSUMER' AND COLUMN_NAME ='PARTNER_SSN';
SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='CM_CONSUMER' AND COLUMN_NAME ='SECOND_PHONE';