SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_SEL_FEATURE' AND COLUMN_NAME ='BASE_NON_RECUR_PRICE';
SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_SEL_FEATURE' AND COLUMN_NAME ='NON_RECUR_PRICE';
SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_SEL_FEATURE' AND COLUMN_NAME ='NON_RECUR_PRICE_U';
SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_SEL_FEATURE' AND COLUMN_NAME ='RECUR_PRICE';
SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_SEL_FEATURE' AND COLUMN_NAME ='RECUR_PRICE_U';
SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_SEL_FEATURE' AND COLUMN_NAME ='INC_PRICE';
SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_SEL_FEATURE' AND COLUMN_NAME ='ON_DELIVERY_PRICE';
SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_SEL_FEATURE' AND COLUMN_NAME ='PRICING_ON';
SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_SEL_FEATURE' AND COLUMN_NAME ='PRICING_STATUS';
SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_SEL_FEATURE' AND COLUMN_NAME ='IS_INCLUDED';
SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_SEL_FEATURE' AND COLUMN_NAME ='IS_REQUIRED';
SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_SEL_FEATURE' AND COLUMN_NAME ='IS_AVAILABLE';
SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_SEL_FEATURE' AND COLUMN_NAME ='IS_DISPLAYABLE';
SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_SEL_FEATURE' AND COLUMN_NAME ='DESCRIPTION';

 