 

SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_LINE_ITEM_DTL' AND COLUMN_NAME ='CATEGORY';

SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_LINE_ITEM_DTL' AND COLUMN_NAME ='NAME';