SELECT '1' AS Expected, COUNT(*) AS Actual FROM DUAL WHERE (SELECT INDEX_NAME FROM ALL_INDEXES WHERE INDEX_NAME ='CONSUMER_ADDRESS_IDX01') IN ('CONSUMER_ADDRESS_IDX01');

SELECT '1' AS Expected, COUNT(*) AS Actual FROM DUAL WHERE (SELECT INDEX_NAME FROM ALL_INDEXES WHERE INDEX_NAME ='CONSUMER_BILLING_IDX01') IN ('CONSUMER_BILLING_IDX01');

SELECT '1' AS Expected, COUNT(*) AS Actual FROM DUAL WHERE (SELECT INDEX_NAME FROM ALL_INDEXES WHERE INDEX_NAME ='CONSUMER_PAYMENT_IDX01') IN ('CONSUMER_PAYMENT_IDX01');

