SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_LINE_ITEM' AND COLUMN_NAME ='EVENT_TYPE';

SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_LINE_ITEM' AND COLUMN_NAME ='IS_EVENT_SELECTED';

SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_LINE_ITEM' AND COLUMN_NAME ='IS_EVENT_COMPLETED';

SELECT '1' AS Expected, COUNT(*) AS Actual FROM DUAL WHERE (SELECT SEQUENCE_NAME FROM ALL_SEQUENCES WHERE SEQUENCE_NAME ='CM_CUST_CSAT_SURVEY_SEQ') IN ('CM_CUST_CSAT_SURVEY_SEQ');

SELECT TO_CHAR('CM_CUSTOMER_SURVEY') VERIFY FROM V_TX.OM_RTIM_ORDER_MAPPING WHERE '1'='0' UNION ALL SELECT 'The script is verified for CM_CUSTOMER_SURVEY' FROM DUAL;

SELECT TO_CHAR('OM_EVENT_TYPE') VERIFY FROM V_TX.OM_RTIM_ORDER_MAPPING WHERE '1'='0' UNION ALL SELECT 'The script is verified for OM_EVENT_TYPE' FROM DUAL;