SELECT '1' AS Expected, COUNT(*) AS Actual FROM DUAL WHERE (SELECT INDEX_NAME FROM ALL_INDEXES WHERE INDEX_NAME ='UAM_USERLOGIN_IDX01') in ('UAM_USERLOGIN_IDX01');

SELECT '1' AS Expected, COUNT(*) AS Actual FROM DUAL WHERE (SELECT INDEX_NAME FROM ALL_INDEXES WHERE INDEX_NAME ='UAM_USR_MDATA_IDX01') in ('UAM_USR_MDATA_IDX01');