
    
ALTER TABLE OM_LINE_ITEM  ADD NON_RECUR_PRICE_U character varying(3)   DEFAULT 'USD';
ALTER TABLE OM_LINE_ITEM  ADD RECUR_PRICE_U character varying(3) DEFAULT 'USD';
ALTER TABLE OM_LINE_ITEM  ADD INC_PRICE BOOLEAN   DEFAULT TRUE;

ALTER TABLE OM_SALES_ORDER  ADD NON_RECUR_PRICE_U character varying(3)   DEFAULT 'USD';
ALTER TABLE OM_SALES_ORDER  ADD RECUR_PRICE_U character varying(3) DEFAULT 'USD';