COMMENT ON TABLE V_tx.om_stat_rec IS 'Information of Order Status';

COMMENT ON COLUMN V_tx.om_stat_rec.id  IS 'Primary key, autogenerated id';
COMMENT ON COLUMN V_tx.om_stat_rec.created_at  IS 'Status added date & time';
COMMENT ON COLUMN V_tx.om_stat_rec.status IS 'order status';
COMMENT ON COLUMN V_tx.om_stat_rec.agent_ext_id IS 'Agent, who updates teh order status';