
CREATE TABLE WEB_PROVIDER (  
	id bigint(20) NOT NULL AUTO_INCREMENT,  
	PROVIDER bigint(20) DEFAULT NULL,  
	URL varchar(255) DEFAULT NULL,  
	CERTIFICATE varchar(255) DEFAULT NULL,  
	PRIMARY KEY (id)
) ;