 


ALTER TABLE OM_SEL_FEATURE ADD COLUMN   BASE_NON_RECUR_PRICE  double precision default 0;
ALTER TABLE OM_SEL_FEATURE ADD COLUMN    NON_RECUR_PRICE   double precision default 0;
ALTER TABLE OM_SEL_FEATURE ADD COLUMN    NON_RECUR_PRICE_U   character varying(3) default 'USD';
ALTER TABLE OM_SEL_FEATURE ADD COLUMN    RECUR_PRICE   double precision default 0;
ALTER TABLE OM_SEL_FEATURE ADD COLUMN    RECUR_PRICE_U   character varying(3) default 'USD';
ALTER TABLE OM_SEL_FEATURE ADD COLUMN    INC_PRICE   boolean default 'true';
ALTER TABLE OM_SEL_FEATURE ADD COLUMN    ON_DELIVERY_PRICE   double precision default 0;
ALTER TABLE OM_SEL_FEATURE ADD COLUMN    PRICING_ON    timestamp without time zone default now();
ALTER TABLE OM_SEL_FEATURE ADD COLUMN    PRICING_STATUS   bigint default 0;
ALTER TABLE OM_SEL_FEATURE ADD COLUMN    IS_INCLUDED boolean default 'true';
ALTER TABLE OM_SEL_FEATURE ADD COLUMN    IS_REQUIRED boolean default 'false';
ALTER TABLE OM_SEL_FEATURE ADD COLUMN    IS_AVAILABLE boolean default 'true';
ALTER TABLE OM_SEL_FEATURE ADD COLUMN    IS_DISPLAYABLE boolean default 'true'; 
ALTER TABLE OM_SEL_FEATURE ADD COLUMN    DESCRIPTION character varying(255);

 