ALTER TABLE CM_ACCOUNT  ADD (BILLING_PHONE VARCHAR2(120)   );
ALTER TABLE CM_ACCOUNT  ADD (CREDIT_CARD_REF VARCHAR2(120)   );
ALTER TABLE CM_ACCOUNT  ADD (IS_AUTHORIZED NUMBER(2)   );
ALTER TABLE CM_ACCOUNT  ADD (SEC_TC_ACCEPT VARCHAR2(60)   );
ALTER TABLE CM_ACCOUNT  ADD (ACCT_TYPE_IND VARCHAR2(60)   );




 