ALTER TABLE CM_CONSUMER ADD CURRENT_EMPLOYED_YEAR VARCHAR2(4);
ALTER TABLE CM_CONSUMER ADD CURRENT_EMPLOYED_MONTH VARCHAR2(2);
ALTER TABLE OM_LINE_ITEM ADD (ON_DELIVERY_PRICE FLOAT default 0 not NULL);