CREATE TABLE OM_LI_ATTRIBUTE
(
  ID NUMBER NOT NULL
, NAME VARCHAR2(500)
, VALUE VARCHAR2(500)
, DESCRIPTION VARCHAR2(4000)
, LINE_ITEM_ID NUMBER
, SOURCE VARCHAR2(50)
);

ALTER TABLE OM_LI_ATTRIBUTE
ADD CONSTRAINT OM_LINE_ITEM_ATTRIBUTE_PK PRIMARY KEY
(
  ID
);

CREATE SEQUENCE OM_LINE_ITEM_ATTRIBUTE_SEQ
	INCREMENT BY 1
	START WITH 100
	NOMAXVALUE
	NOMINVALUE
	NOCYCLE
	CACHE 20
	NOORDER;


CREATE TABLE OM_LINE_ITEM_OM_LI_ATTRIBUTE
(
  OM_LINE_ITEM_ID NUMBER
, LINEITEMATTRIBUTE_ID NUMBER
);

ALTER TABLE OM_LINE_ITEM_OM_LI_ATTRIBUTE
ADD CONSTRAINT FK_OM_LINE_ITEM_OM_LI_ATTRIB FOREIGN KEY
(
  OM_LINE_ITEM_ID
)
REFERENCES OM_LINE_ITEM
(
  ID
);


