CREATE TABLE OM_SYSTEM_REASON
(
  ID NUMBER NOT NULL
, CODE VARCHAR2(20)
, DESCRIPTION VARCHAR2(120)
, CREATED_ON DATE DEFAULT SYSDATE
, UPDATED_ON DATE DEFAULT SYSDATE
, CONTEXT VARCHAR2(20) DEFAULT ''
);

ALTER TABLE OM_SYSTEM_REASON ADD CONSTRAINT id_unique UNIQUE(ID);
ALTER TABLE OM_SYSTEM_REASON ADD CONSTRAINT code_unique UNIQUE(CODE);
 

insert into OM_SYSTEM_ERROR_REASON(id, code, description) values (1,'9999','OUT OF MEMORY');