SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_LINE_ITEM' AND COLUMN_NAME ='is_new';
SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_LINE_ITEM' AND COLUMN_NAME ='DISCONNECT_ON';
SELECT '1' as EXPECTED, COUNT(*) as ACTUAL FROM ALL_TAB_COLUMNS WHERE TABLE_NAME ='OM_LINE_ITEM' AND COLUMN_NAME ='ORDERED_ON';