/* This code contains copyright information which is the proprietary property
 * of   Advanced Travel Solutions. No part of this code may be reproduced,
 * stored or transmitted in any form without the prior written permission of
 *   Advanced Travel Solutions.
 *
 * Copyright   Advanced Travel Solutions 2011
 * Confidential. All rights reserved.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.07.31 at 10:52:58 AM BST
//

package abc.xyz.pts.bcs.common.irisk.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for PR_ADD_TRAVELLER_ALERT_LOG complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="PR_ADD_TRAVELLER_ALERT_LOG">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="TRAVELLER_ALERT_ID" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="ACTION_TYPE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="REMARK" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="REC_FULL_NAME" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="AIRPORT_CODE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="RE_ROUTED_AIRPORT_CODE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ROLES_NOTIFIED" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="MEDIA_TYPE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ACTION_STATUS" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ACTION_ERROR_MESSAGE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="RECIPIENT_CATEGORY" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="MESSAGE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SESSION_ID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PR_ADD_TRAVELLER_ALERT_LOG", namespace = "PR_ADD_TRAVELLER_ALERT_LOG")
public class PrAddTravellerAlertLog {

    @XmlAttribute(name = "TRAVELLER_ALERT_ID")
    protected Long travellerAlertId;
    @XmlAttribute(name = "ACTION_TYPE")
    protected String actionType;
    @XmlAttribute(name = "REMARK")
    protected String remark;
    @XmlAttribute(name = "REC_FULL_NAME")
    protected String recFullName;
    @XmlAttribute(name = "AIRPORT_CODE")
    protected String airportCode;
    @XmlAttribute(name = "RE_ROUTED_AIRPORT_CODE")
    protected String reRoutedAirportCode;
    @XmlAttribute(name = "ROLES_NOTIFIED")
    protected String rolesNotified;
    @XmlAttribute(name = "MEDIA_TYPE")
    protected String mediaType;
    @XmlAttribute(name = "ACTION_STATUS")
    protected String actionStatus;
    @XmlAttribute(name = "ACTION_ERROR_MESSAGE")
    protected String actionErrorMessage;
    @XmlAttribute(name = "RECIPIENT_CATEGORY")
    protected String recipientCategory;
    @XmlAttribute(name = "MESSAGE")
    protected String message;
    @XmlAttribute(name = "SESSION_ID")
    protected String sessionId;

    /**
     * Gets the value of the travellerAlertId property.
     *
     * @return possible object is {@link Long }
     *
     */
    public Long getTravellerAlertId() {
        return travellerAlertId;
    }

    /**
     * Sets the value of the travellerAlertId property.
     *
     * @param value
     *            allowed object is {@link Long }
     *
     */
    public void setTravellerAlertId(final Long value) {
        this.travellerAlertId = value;
    }

    /**
     * Gets the value of the actionType property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getActionType() {
        return actionType;
    }

    /**
     * Sets the value of the actionType property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setActionType(final String value) {
        this.actionType = value;
    }

    /**
     * Gets the value of the remark property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getRemark() {
        return remark;
    }

    /**
     * Sets the value of the remark property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setRemark(final String value) {
        this.remark = value;
    }

    /**
     * Gets the value of the recFullName property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getRecFullName() {
        return recFullName;
    }

    /**
     * Sets the value of the recFullName property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setRecFullName(final String value) {
        this.recFullName = value;
    }

    /**
     * Gets the value of the airportCode property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getAirportCode() {
        return airportCode;
    }

    /**
     * Sets the value of the airportCode property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setAirportCode(final String value) {
        this.airportCode = value;
    }

    /**
     * Gets the value of the reRoutedAirportCode property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getReRoutedAirportCode() {
        return reRoutedAirportCode;
    }

    /**
     * Sets the value of the reRoutedAirportCode property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setReRoutedAirportCode(final String value) {
        this.reRoutedAirportCode = value;
    }

    /**
     * Gets the value of the rolesNotified property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getRolesNotified() {
        return rolesNotified;
    }

    /**
     * Sets the value of the rolesNotified property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setRolesNotified(final String value) {
        this.rolesNotified = value;
    }

    /**
     * Gets the value of the mediaType property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getMediaType() {
        return mediaType;
    }

    /**
     * Sets the value of the mediaType property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setMediaType(final String value) {
        this.mediaType = value;
    }

    /**
     * Gets the value of the actionStatus property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getActionStatus() {
        return actionStatus;
    }

    /**
     * Sets the value of the actionStatus property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setActionStatus(final String value) {
        this.actionStatus = value;
    }

    /**
     * Gets the value of the actionErrorMessage property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getActionErrorMessage() {
        return actionErrorMessage;
    }

    /**
     * Sets the value of the actionErrorMessage property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setActionErrorMessage(final String value) {
        this.actionErrorMessage = value;
    }

    /**
     * Gets the value of the recipientCategory property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getRecipientCategory() {
        return recipientCategory;
    }

    /**
     * Sets the value of the recipientCategory property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setRecipientCategory(final String value) {
        this.recipientCategory = value;
    }

    /**
     * Gets the value of the message property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setMessage(final String value) {
        this.message = value;
    }

    /**
     * Gets the value of the sessionId property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * Sets the value of the sessionId property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setSessionId(final String value) {
        this.sessionId = value;
    }

}
