SELECT * from OM_STAT_REC_REASONS where ELEMENT = '90';



SELECT * FROM V_TX.OM_SALES_ORDER where EXTERNAL_ID = '6419';
 
SELECT * from OM_STAT_REC where ID in (SELECT CURRENT_STATUS_ID FROM V_TX.OM_SALES_ORDER where EXTERNAL_ID = '6419');


UPDATE V_TX.OM_SALES_ORDER SET ALL_CONNECT_ACCT_NUM = null where EXTERNAL_ID = '6419';
UPDATE V_TX.OM_SALES_ORDER SET ALL_CONNECT_ACCT_NUM = '123' where EXTERNAL_ID = '6419';
UPDATE V_TX.OM_SALES_ORDER SET  CURRENT_STATUS_ID = null where EXTERNAL_ID = '6419';