SELECT '1' AS Expected, COUNT(*) AS Actual FROM DUAL WHERE (SELECT INDEX_NAME FROM ALL_INDEXES WHERE INDEX_NAME ='OM_BROAD_EXTID_IDX01') in ('OM_BROAD_EXTID_IDX01');
SELECT '1' AS Expected, COUNT(*) AS Actual FROM DUAL WHERE (SELECT INDEX_NAME FROM ALL_INDEXES WHERE INDEX_NAME ='OM_BROAD_GUID_IDX01') in ('OM_BROAD_GUID_IDX01');
SELECT '1' AS Expected, COUNT(*) AS Actual FROM DUAL WHERE (SELECT INDEX_NAME FROM ALL_INDEXES WHERE INDEX_NAME ='OM_BROAD_DT_IDX01') in ('OM_BROAD_DT_IDX01');

SELECT '1' AS Expected, COUNT(*) AS Actual FROM DUAL WHERE (SELECT SEQUENCE_NAME FROM ALL_SEQUENCES WHERE SEQUENCE_NAME ='OM_BROADCAST_SEQ') IN ('OM_BROADCAST_SEQ');

SELECT TO_CHAR('OM_BROADCAST') VERIFY FROM V_TX.OM_RTIM_ORDER_MAPPING WHERE '1'='0' UNION ALL SELECT 'The script is verified for OM_BROADCAST' FROM DUAL;