ALTER TABLE V_TX.CM_CONSUMER ALTER COLUMN BIRTH_INFO character varying(1000);
ALTER TABLE V_TX.CM_CONSUMER ALTER COLUMN DRIVER_LICENSE_NO character varying(1000);
ALTER TABLE V_TX.CM_CONSUMER ALTER COLUMN SSN character varying(1000);
ALTER TABLE V_TX.CM_CONSUMER ALTER COLUMN PIN character varying(1000);
ALTER TABLE V_TX.CM_CONSUMER ALTER COLUMN SECURITY_ANSWER character varying(1000);
ALTER TABLE V_TX.CM_CONSUMER ALTER COLUMN PARTNER_SSN character varying(1000);

ALTER TABLE V_TX.CM_BILLING_INFORMATION ALTER COLUMN EXPIRE_MONTH character varying(1000);
ALTER TABLE V_TX.CM_BILLING_INFORMATION ALTER COLUMN EXPIRE_YEAR character varying(1000);
ALTER TABLE V_TX.CM_BILLING_INFORMATION ALTER COLUMN CREDIT_CARD_NUMBER  character varying(1000);
ALTER TABLE V_TX.CM_BILLING_INFORMATION ALTER COLUMN CARD_HOLDER_NAME  character varying(1000);
ALTER TABLE V_TX.CM_BILLING_INFORMATION ALTER COLUMN CHECKING_ACCOUNT_NUMBER  character varying(1000);
ALTER TABLE V_TX.CM_BILLING_INFORMATION ALTER COLUMN ROUTING_NUMBER character varying(1000);


ALTER TABLE V_TX.OM_JOB ALTER COLUMN STATUS_QUEUED TYPE character varying(30);

