COMMENT ON TABLE V_tx.cm_customer_audit IS 'This table store customer auditiong information';

COMMENT ON COLUMN V_tx.cm_customer_audit.id IS 'Autogenerated unique ID number';
COMMENT ON COLUMN V_tx.cm_customer_audit.audit_on IS 'Date when information was audited';
COMMENT ON COLUMN V_tx.cm_customer_audit.customer_id IS 'Customer external id';
COMMENT ON COLUMN V_tx.cm_customer_audit.description IS 'Audit description';
COMMENT ON COLUMN V_tx.cm_customer_audit.detail IS 'Holds updated customer information';
COMMENT ON COLUMN V_tx.cm_customer_audit.agent_id IS 'Agent id who has performed customer update';