ALTER TABLE CM_CONSUMER ADD COLUMN    BEST_PHONE_CONTACT character varying(30);
ALTER TABLE CM_CONSUMER ADD COLUMN    PARTNER_NAME character varying(100);
ALTER TABLE CM_CONSUMER ADD COLUMN    PARTNER_SSN character varying(15);
ALTER TABLE CM_CONSUMER ADD COLUMN    SECOND_PHONE character varying(30);


 