COMMENT ON TABLE V_tx.om_line_item_dtl IS 'LineItem detail informaiton';

COMMENT ON COLUMN V_tx.om_line_item_dtl.id IS 'Primary key';
COMMENT ON COLUMN V_tx.om_line_item_dtl.lineitem_detail_ext_id IS 'Product/Promotion external id';
COMMENT ON COLUMN V_tx.om_line_item_dtl.line_item_type IS 'Detail type of the product. Should be either Product or ProductPromotion';
COMMENT ON COLUMN V_tx.om_line_item_dtl.applies_to IS 'If lineitem is promotion then this field store to which product this promotion applie to';
COMMENT ON COLUMN V_tx.om_line_item_dtl.product_unique_id IS 'Unique id generated by product service when product was snapshot. For harmony orders this field contains unique id generated by system';
COMMENT ON COLUMN V_tx.om_line_item_dtl.category IS 'Product/Promotion category';
COMMENT ON COLUMN V_tx.om_line_item_dtl.name IS 'Name of the product';

